
F1::
   Send, {LCtrl Down}x{LCtrl Up}

Return

	  
F2::
   SendInput %clipboard%
   send {enter}
   Sleep, 1000
   Click 300,360
   Sleep, 6000
   Click 410,315
   Sleep, 1000
   SendInput, ^b^uSFHQ S&R Team^u^b 
   Send, `r
   SendInput, Please capture this tracker as a C2-12 OFFA.  Thanks{!}
   Send, `r
   Send, `r
   SendInput, ^b^uTIP Shipping Team^u^b 
   Send, `r
   SendInput, If you pick up this case please refund or replace with normal workflows.  Thanks{!}
   Sleep, 500
   Click 1500,565

return
 
F3::
   Click 410,315
   Sleep, 1000
   SendInput, ^b^uSFHQ S&R Team^u^b 
   Send, `r
   SendInput, Please capture this tracker as a C2-12 OFFA.  Thanks{!}
   Send, `r
   Send, `r
   SendInput, ^b^uTIP Shipping Team^u^b 
   Send, `r
   SendInput, If you pick up this case please refund or replace with normal workflows.  Thanks{!}
   Sleep, 500
   Click 1500,565
   
Return